# Generated by Django 4.0.1 on 2022-01-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_kasten_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zettel',
            name='related',
            field=models.ManyToManyField(blank=True, to='api.Zettel'),
        ),
        migrations.AlterField(
            model_name='zettel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.Tag'),
        ),
    ]
