version: '3.5'
services:
  database:
    container_name: postgres
    image: postgres:latest
    env_file: database.conf
    ports:
      - 5432:5432
    networks:
      - main_network
    volumes:
      - db_volume:/var/lib/postgresql/data

  web:
    build: .
    env_file: database.conf
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - database
    networks:
      - main_network

#  populate:
#    build: populate/.
#    depends_on:
#      - web
#    env_file: database.conf
#    networks:
#      - main_network

volumes:
  db_volume:
    driver: local

networks:
  main_network:
    driver: bridge